# Generated by Django 4.0.2 on 2022-02-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_alter_movie_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('E', 'Euro'), ('D', 'Dollar'), ('R', 'Rubles')], default='D', max_length=1),
        ),
    ]
