# Generated by Django 4.0.2 on 2022-02-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0012_alter_movie_budget_alter_movie_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='Quentin Tarantino', max_length=100),
        ),
    ]
