# Generated by Django 4.0.2 on 2022-02-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0013_movie_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=100),
        ),
    ]
